//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public int CampaignID { get; set; }
        public string Campaign_name { get; set; }
        public string Keywords { get; set; }
        public int Bid_amount { get; set; }
        public int Campaign_fund { get; set; }
        public string Status { get; set; }
        public string Town { get; set; }
        public int Radius { get; set; }
    }
}
